### ISSUE TITLE
stack user required could cause issues if not checked

### ISSUE THREAD

**Issue by elfosardo** [metalkube/dev-scripts#28]
The scripts assume that the user 'stack' will be used to run the process but there's no check to verify and/or enforce that it's the actual user running the commands.
This could cause some issues during the process, e.g.
```
cat: /home/stack/ironic_nodes.json: Permission denied
```
due to the stack home dir being set by default at 700
A workaround exists for this issue, but others could arise.
In general, having the stack user hardcoded is not ideal.

**Comment by hardys** [comment]
Note it's not hard-coded, there's a non_root_user variable in the ansible roles which require this, but we could just assume $USER for this, or modify the roles to not assume a specific non_root_user

Agree we should probably at least validate this - it's mentioned in the README but perhaps we're missing some steps automating the setup of the user in the scripts?

**Comment by elfosardo** [comment]
IMHO having a separate user is a good choice, an alternative could be a working dir, especially because the home/working-dir needs to be world-accessible.
We can even leave the stack user, the first thing to do should be validate if the user actually exist and has the correct permission, a create-user script can improve the automation.
A basic workflow could be:
- validate user, if it doesn't exist create it, or ask to create it
- validate the working-dir/home
- copy (download?) the repo to the home/working dir and switch to it
- switch to the new user
- start the process

**Comment by hardys** [comment]
Note #36 solved one part of this, e.g open up the permissions on the stack homedir.

I do agree a working dir may be preferable though - and the tripleo-quickstart project where I took these roles from did exactly that (cloned everything to ~/.quickstart and ran things from there)

I was also trying to keep this simple though, e.g running the local roles vs cloning by default (which quickstart does), which makes development easier.

So perhaps the best approach is to just run everything as the local $USER but create a temporary directory, I'm open to either approach.

**Comment by elfosardo** [comment]
I'm currently working on a change to use the local $USER and a working dir
We'll open a PR soon
